# Quelle der Vorlage: https://de.vitejs.dev/guide/static-deploy#github-pages

# Einfacher Workflow zur Bereitstellung von statischem Inhalt auf GitHub-Pages
name: Statischen Inhalt auf Pages bereitstellen

on:
  ## Wird bei Pushes auf den Standard-Zweig ausgeführt
  #push:
  #  branches: ['main']
  workflow_dispatch:

# Setzt die GITHUB_TOKEN-Berechtigungen, um die Bereitstellung auf GitHub-Pages zu ermöglichen
permissions:
  contents: read
  pages: write
  id-token: write

# Ermöglicht eine gleichzeitige Bereitstellung. Wenn Wenn ein neues Deployment gestartet wird, 
# während ein anderes noch läuft, wird das ältere abgebrochen.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
        # Upload des dist-Ordners
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

